### ISSUE TITLE
install via cocoa pods in swift/x-code 7.3 throws error in turbolinks framework

### ISSUE THREAD

**Issue by Rovel** [turbolinks/turbolinks-ios#68] opened 2016-09-19 19:31 UTC
I've just started a new project to test Turbolinks cocoa pod and it throws an error before even importing the project. here are some screenshots:

Inital project configs:
![captura de tela 2016-09-19 as 16 11 29](https://cloud.githubusercontent.com/assets/2469500/18645827/2c55bf50-7e85-11e6-8239-1f22c6f2f715.png)

Error in Turbolinks lib: (VisitableView.swift)
![captura de tela 2016-09-19 as 16 11 36](https://cloud.githubusercontent.com/assets/2469500/18645847/43701a96-7e85-11e6-83e1-5f7c2e6bda4a.png)

I tried in 3 different projects with cocoa pods and without core data as the inital config.

I can't even import turbolinks to a file.....

**Comment by apbendi** [comment] 2016-09-21 13:43
hey @Rovel, I'm not on the Turbolinks team, but my guess is the issue is due to using Xcode 7.3 and Swift 2.2, instead of Xcode 8 and Swift 2.3. Is there a reason your projects haven't updated yet? If so, you might have luck pinning to an older commit, from before they upgraded the repo for the latest versions: 6ea0fa992a1442903a9224ef85e87946badabc55 (you can do this with CocoPods by specifying the `:commit => SHA` parameter).

Just remember, you won't be getting any new changes that are made or merged in until you upgrade and unpin.

**Comment by zachwaugh** [comment] 2016-11-28 20:29
@apbendi is correct, Turbolinks requires Xcode 8 (or later) and Swift 2.3 currently. There is also a `swift-3.0` branch, but Xcode 7 isn't supported. That error is related to a change in the iOS 10 SDK.

**Closed by zachwaugh** 2016-11-28 20:29 UTC
