### ISSUE TITLE
Question about screenshot

### ISSUE THREAD

**Issue by carlesjove** [turbolinks/turbolinks-ios#119] opened 2017-11-21 11:10 UTC
Hi,

I'm cross posting an issue I opened in Turbolink's repo: https://github.com/turbolinks/turbolinks/issues/322

I've been struggling with controlling the look of a page before a screenshot is taken for cache. For the sake of the example, assume I want to close a modal window before page is cached. I assumed that any changes I made to the DOM in `turbolinks:before-cache` would take place before iOS takes a screenshot when [VisitableView#updateScreenshot](https://github.com/turbolinks/turbolinks-ios/blob/master/Turbolinks/VisitableView.swift#L131) is executed, but this seems not to be the case. I have even tried to execute JavaScript to close the modal window within `VisitableView#updateScreenshot` _before_ the screenshot is taken, unsuccesfully (cached page DOM is not changed).

I'm not sure whether this is a bug or I'm not understanding how the process works. Any tip is welcome, and I could try to write something for the docs once I properly understand.

Thanks very much :-)

**Comment by zachwaugh** [comment] 2018-02-13 16:28
Hi @carlesjove, sorry the delay in responding to your question. I'd have to look deeper to say for sure, but I'm assuming the issue is the we take the screenshot before the changes made in `turbolinks:before-cache` are actually rendered. When we take a snapshot, we send false param to the method: `webView.snapshotView(afterScreenUpdates: false)`, that means it will take a screenshot before queued updates are rendered to the screen. We can't delay the snapshot or pass `true` there, since the webview will be removed from the screen by then and be blank. You could try closing the modal before starting the navigation to ensure the screen has been updated.

**Closed by zachwaugh** 2018-02-13 16:28 UTC
